twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        yandex_key: '%app.yandex.key%'

when@test:
    twig:
        strict_variables: true
